# Generated by Django 6.0.2 on 2026-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=160, null=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('otp_hash', models.CharField(blank=True, max_length=256)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
