# Generated by Django 5.1.3 on 2026-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ordershippingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_action_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
